version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nft-collections-front
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
